{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "PATH_CURRENT = '/home/jupyter'\n",
    "PATH_MODEL = f'{PATH_CURRENT}/meme_hateful_detection/models'\n",
    "\n",
    "# module_path = PATH_CURRENT\n",
    "if PATH_CURRENT not in sys.path:\n",
    "    sys.path.append(PATH_CURRENT)\n",
    "if PATH_MODEL not in sys.path:\n",
    "    sys.path.append(PATH_MODEL)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "# import meme_hateful_detection.processors.processors\n",
    "# import meme_hateful_detection.models.concat_vl"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "| Baseline         | Model Key      | Pretrained Key                                   | Baseine Config                                                     |\n",
    "|------------------|----------------|--------------------------------------------------|------------------------------------------------------------|\n",
    "| Image-Grid       | unimodal_image | unimodal_image.hateful_memes.images              | projects/hateful_memes/configs/unimodal/image.yaml         |\n",
    "| Image-Region     | unimodal_image | unimodal_image.hateful_memes.features            | projects/hateful_memes/configs/unimodal/with_features.yaml |\n",
    "| Text BERT        | unimodal_text  | unimodal_text.hateful_memes.bert                 | projects/hateful_memes/configs/unimodal/bert.yaml          |\n",
    "| Late Fusion      | late_fusion    | late_fusion.hateful_memes                        | projects/hateful_memes/configs/late_fusion/defaults.yaml   |\n",
    "| ConcatBERT       | concat_bert    | concat_bert.hateful_memes                        | projects/hateful_memes/configs/concat_bert/defaults.yaml   |\n",
    "| MMBT-Grid        | mmbt           | mmbt.hateful_memes.images                        | projects/hateful_memes/configs/mmbt/defaults.yaml          |\n",
    "| MMBT-Region      | mmbt           | mmbt.hateful_memes.features                      | projects/hateful_memes/configs/mmbt/with_features.yaml     |\n",
    "| ViLBERT          | vilbert        | vilbert.finetuned.hateful_memes.direct           | projects/hateful_memes/configs/vilbert/defaults.yaml       |\n",
    "| Visual BERT      | visual_bert    | visual_bert.finetuned.hateful_memes.direct       | projects/hateful_memes/configs/visual_bert/direct.yaml     |\n",
    "| ViLBERT CC       | vilbert        | vilbert.finetuned.hateful_memes.from_cc_original | projects/hateful_memes/configs/vilbert/from_cc.yaml        |\n",
    "| Visual BERT COCO | visual_bert    | visual_bert.finetuned.hateful_memes.from_coco    | projects/hateful_memes/configs/visual_bert/from_coco.yaml  |"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_model_config = pd.read_csv(f'{PATH_MODEL}/model_config.csv', sep = ';')\n",
    "df_model_config.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "sys.argv = ['mmf_predict', 'config=/home/jupyter/meme_hateful_detection/configs/unimodal/image.yaml', 'model=unimodal_image', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=unimodal_image.hateful_memes.images']\n",
    "str_exec = ' '.join(sys.argv)\n",
    "# !{str_exec}\n",
    "print(str_exec)\n",
    "# !mmf_predict config=/home/jupyter/meme_hateful_detection/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes run_type=test checkpoint.resume_zoo=unimodal_image.hateful_memes.images\n",
    "# !mmf_predict config=/home/jupyter/meme_hateful_detection/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes run_type=test checkpoint.resume_zoo=unimodal_image.hateful_memes.images\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/unimodal/image.yaml', 'model=unimodal_image', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=unimodal_image.hateful_memes.images', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "Overriding option config to ../configs/unimodal/image.yaml\n",
      "Overriding option model to unimodal_image\n",
      "Overriding option datasets to hateful_memes\n",
      "Overriding option run_type to test\n",
      "Overriding option checkpoint.resume_zoo to unimodal_image.hateful_memes.images\n",
      "Overriding option evaluation.predict to true\n",
      "Using seed 16942113\n",
      "Logging to: ./save/logs/train_2020-05-30T01:28:16.log\n",
      "2020-05-30T01:28:16 INFO: Loading datasets\n",
      "2020-05-30T01:28:28 INFO: Torch version is: 1.5.0\n",
      "2020-05-30T01:28:28 INFO: Loading checkpoint\n",
      "2020-05-30T01:28:32 WARNING: /home/jupyter/mmf/mmf/utils/checkpoint.py:224: UserWarning: 'optimizer' key is not present in the checkpoint asked to be loaded. Skipping.\n",
      "  \"'optimizer' key is not present in the \"\n",
      "\n",
      "2020-05-30T01:28:32 INFO: Checkpoint loaded\n",
      "2020-05-30T01:28:32 INFO: Starting test inference predictions\n",
      "2020-05-30T01:28:32 INFO: Predicting for hateful_memes\n",
      "100%|███████████████████████████████████████████| 32/32 [04:48<00:00,  9.00s/it]\n",
      "2020-05-30T01:33:20 INFO: Wrote evalai predictions for hateful_memes to /home/jupyter/meme_hateful_detection/notebooks/save/hateful_memes_unimodal_image_16942113/reports/hateful_memes_run_test_2020-05-30T01:33:20.csv\n",
      "2020-05-30T01:33:20 INFO: Finished predicting\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/unimodal/with_features.yaml', 'model=unimodal_image', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=unimodal_image.hateful_memes.features', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "/opt/conda/lib/python3.7/site-packages/omegaconf/dictconfig.py:252: UserWarning: Keys with dot (../../../others/unimodal/configs/hateful_memes/with_features.yaml) are deprecated and will have different semantic meaning the next major version of OmegaConf (2.1)\n",
      "See the compact keys issue for more details: https://github.com/omry/omegaconf/issues/152\n",
      "You can disable this warning by setting the environment variable OC_DISABLE_DOT_ACCESS_WARNING=1\n",
      "  warnings.warn(message=msg, category=UserWarning)\n",
      "Overriding option config to ../configs/unimodal/with_features.yaml\n",
      "Overriding option model to unimodal_image\n",
      "Overriding option datasets to hateful_memes\n",
      "Overriding option run_type to test\n",
      "Overriding option checkpoint.resume_zoo to unimodal_image.hateful_memes.features\n",
      "Overriding option evaluation.predict to true\n",
      "Using seed 23408258\n",
      "Logging to: ./save/logs/train_2020-05-30T01:33:23.log\n",
      "2020-05-30T01:33:23 INFO: Loading datasets\n",
      "2020-05-30T01:33:27 WARNING: /home/jupyter/mmf/mmf/models/base_model.py:97: UserWarning: No losses are defined in model configuration. You are expected to return loss in your return dict from forward.\n",
      "  \"No losses are defined in model configuration. You are expected \"\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 89, in run\n",
      "    main(configuration, predict=predict)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 36, in main\n",
      "    trainer.load()\n",
      "  File \"/home/jupyter/mmf/mmf/trainers/base_trainer.py\", line 61, in load\n",
      "    self.load_model_and_optimizer()\n",
      "  File \"/home/jupyter/mmf/mmf/trainers/base_trainer.py\", line 124, in load_model_and_optimizer\n",
      "    self.optimizer = build_optimizer(self.model, self.config)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/build.py\", line 161, in build_optimizer\n",
      "    \"Optimizer attributes must have a 'type' key \"\n",
      "ValueError: Optimizer attributes must have a 'type' key specifying the type of optimizer. (Custom or PyTorch)\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/unimodal/bert.yaml', 'model=unimodal_text', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=unimodal_text.hateful_memes.bert', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "/opt/conda/lib/python3.7/site-packages/omegaconf/dictconfig.py:252: UserWarning: Keys with dot (../../../others/unimodal/configs/hateful_memes/bert.yaml) are deprecated and will have different semantic meaning the next major version of OmegaConf (2.1)\n",
      "See the compact keys issue for more details: https://github.com/omry/omegaconf/issues/152\n",
      "You can disable this warning by setting the environment variable OC_DISABLE_DOT_ACCESS_WARNING=1\n",
      "  warnings.warn(message=msg, category=UserWarning)\n",
      "Overriding option config to ../configs/unimodal/bert.yaml\n",
      "Overriding option model to unimodal_text\n",
      "Overriding option datasets to hateful_memes\n",
      "Overriding option run_type to test\n",
      "Overriding option checkpoint.resume_zoo to unimodal_text.hateful_memes.bert\n",
      "Overriding option evaluation.predict to true\n",
      "Using seed 30690247\n",
      "Logging to: ./save/logs/train_2020-05-30T01:33:30.log\n",
      "2020-05-30T01:33:30 INFO: Loading datasets\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 89, in run\n",
      "    main(configuration, predict=predict)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 36, in main\n",
      "    trainer.load()\n",
      "  File \"/home/jupyter/mmf/mmf/trainers/base_trainer.py\", line 61, in load\n",
      "    self.load_model_and_optimizer()\n",
      "  File \"/home/jupyter/mmf/mmf/trainers/base_trainer.py\", line 113, in load_model_and_optimizer\n",
      "    self.model = build_model(attributes)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/build.py\", line 41, in build_model\n",
      "    model.build()\n",
      "  File \"/home/jupyter/mmf/mmf/models/unimodal.py\", line 51, in build\n",
      "    self.base = UnimodalBase(self.config)\n",
      "  File \"/home/jupyter/mmf/mmf/models/unimodal.py\", line 15, in __init__\n",
      "    super().__init__(config, *args, **kwargs)\n",
      "  File \"/home/jupyter/mmf/mmf/modules/encoders.py\", line 208, in __init__\n",
      "    self.build()\n",
      "  File \"/home/jupyter/mmf/mmf/models/unimodal.py\", line 18, in build\n",
      "    encoders = self._build_encoders(self.config)\n",
      "  File \"/home/jupyter/mmf/mmf/modules/encoders.py\", line 227, in _build_encoders\n",
      "    text_encoder = build_text_encoder(config.text_encoder)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/build.py\", line 216, in build_text_encoder\n",
      "    text_encoder = TextEncoder(config, *args, **kwargs)\n",
      "  File \"/home/jupyter/mmf/mmf/modules/encoders.py\", line 147, in __init__\n",
      "    self.module = TextEmbeddingEncoder(config.params)\n",
      "  File \"/home/jupyter/mmf/mmf/modules/encoders.py\", line 162, in __init__\n",
      "    self._embedding_params.type, **self._embedding_params.params\n",
      "  File \"/home/jupyter/mmf/mmf/modules/embeddings.py\", line 30, in __init__\n",
      "    self.module = VocabEmbedding(**kwargs)\n",
      "  File \"/home/jupyter/mmf/mmf/modules/embeddings.py\", line 58, in __init__\n",
      "    self.vocab = Vocab(**vocab_params)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/vocab.py\", line 40, in __init__\n",
      "    self.vocab = IntersectedVocab(*args, **params)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/vocab.py\", line 277, in __init__\n",
      "    super().__init__(vocab_file, *args, **kwargs)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/vocab.py\", line 125, in __init__\n",
      "    raise RuntimeError(\"Vocab not found at \" + vocab_file)\n",
      "RuntimeError: Vocab not found at /home/jupyter/.cache/torch/mmf/data/vocabs/vocabulary_100k.txt\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/late_fusion/defaults.yaml', 'model=late_fusion', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=late_fusion.hateful_memes', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 58, in run\n",
      "    configuration = Configuration(args)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 210, in __init__\n",
      "    other_configs = self._build_other_configs()\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 227, in _build_other_configs\n",
      "    user_config = self._build_user_config(opts_config)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 253, in _build_user_config\n",
      "    user_config = load_yaml(self.config_path)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 30, in load_yaml\n",
      "    raise e\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 23, in load_yaml\n",
      "    mapping = OmegaConf.load(abs_f)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/omegaconf/omegaconf.py\", line 246, in load\n",
      "    with io.open(os.path.abspath(file_), \"r\", encoding=\"utf-8\") as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/jupyter/meme_hateful_detection/configs/late_fusion/defaults.yaml'\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/concat_bert/defaults.yaml', 'model=concat_bert', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=concat_bert.hateful_memes', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "/opt/conda/lib/python3.7/site-packages/omegaconf/dictconfig.py:252: UserWarning: Keys with dot (../../../others/concat_bert/hateful_memes/defaults.yaml) are deprecated and will have different semantic meaning the next major version of OmegaConf (2.1)\n",
      "See the compact keys issue for more details: https://github.com/omry/omegaconf/issues/152\n",
      "You can disable this warning by setting the environment variable OC_DISABLE_DOT_ACCESS_WARNING=1\n",
      "  warnings.warn(message=msg, category=UserWarning)\n",
      "Overriding option config to ../configs/concat_bert/defaults.yaml\n",
      "Overriding option model to concat_bert\n",
      "Overriding option datasets to hateful_memes\n",
      "Overriding option run_type to test\n",
      "Overriding option checkpoint.resume_zoo to concat_bert.hateful_memes\n",
      "Overriding option evaluation.predict to true\n",
      "Using seed 38555347\n",
      "Logging to: ./save/logs/train_2020-05-30T01:33:38.log\n",
      "2020-05-30T01:33:38 INFO: Loading datasets\n",
      "2020-05-30T01:33:49 WARNING: /home/jupyter/mmf/mmf/models/base_model.py:97: UserWarning: No losses are defined in model configuration. You are expected to return loss in your return dict from forward.\n",
      "  \"No losses are defined in model configuration. You are expected \"\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 89, in run\n",
      "    main(configuration, predict=predict)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 36, in main\n",
      "    trainer.load()\n",
      "  File \"/home/jupyter/mmf/mmf/trainers/base_trainer.py\", line 61, in load\n",
      "    self.load_model_and_optimizer()\n",
      "  File \"/home/jupyter/mmf/mmf/trainers/base_trainer.py\", line 124, in load_model_and_optimizer\n",
      "    self.optimizer = build_optimizer(self.model, self.config)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/build.py\", line 161, in build_optimizer\n",
      "    \"Optimizer attributes must have a 'type' key \"\n",
      "ValueError: Optimizer attributes must have a 'type' key specifying the type of optimizer. (Custom or PyTorch)\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/mmbt/defaults.yaml', 'model=mmbt', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=mmbt.hateful_memes.images', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 58, in run\n",
      "    configuration = Configuration(args)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 210, in __init__\n",
      "    other_configs = self._build_other_configs()\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 227, in _build_other_configs\n",
      "    user_config = self._build_user_config(opts_config)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 253, in _build_user_config\n",
      "    user_config = load_yaml(self.config_path)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 30, in load_yaml\n",
      "    raise e\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 23, in load_yaml\n",
      "    mapping = OmegaConf.load(abs_f)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/omegaconf/omegaconf.py\", line 246, in load\n",
      "    with io.open(os.path.abspath(file_), \"r\", encoding=\"utf-8\") as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/jupyter/meme_hateful_detection/configs/mmbt/defaults.yaml'\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/mmbt/with_features.yaml', 'model=mmbt', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=mmbt.hateful_memes.features', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 58, in run\n",
      "    configuration = Configuration(args)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 210, in __init__\n",
      "    other_configs = self._build_other_configs()\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 227, in _build_other_configs\n",
      "    user_config = self._build_user_config(opts_config)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 253, in _build_user_config\n",
      "    user_config = load_yaml(self.config_path)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 30, in load_yaml\n",
      "    raise e\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 23, in load_yaml\n",
      "    mapping = OmegaConf.load(abs_f)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/omegaconf/omegaconf.py\", line 246, in load\n",
      "    with io.open(os.path.abspath(file_), \"r\", encoding=\"utf-8\") as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/jupyter/meme_hateful_detection/configs/mmbt/with_features.yaml'\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/vilbert/defaults.yaml', 'model=vilbert', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=vilbert.finetuned.hateful_memes.direct', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 58, in run\n",
      "    configuration = Configuration(args)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 210, in __init__\n",
      "    other_configs = self._build_other_configs()\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 227, in _build_other_configs\n",
      "    user_config = self._build_user_config(opts_config)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 253, in _build_user_config\n",
      "    user_config = load_yaml(self.config_path)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 30, in load_yaml\n",
      "    raise e\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 23, in load_yaml\n",
      "    mapping = OmegaConf.load(abs_f)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/omegaconf/omegaconf.py\", line 246, in load\n",
      "    with io.open(os.path.abspath(file_), \"r\", encoding=\"utf-8\") as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/jupyter/meme_hateful_detection/configs/vilbert/defaults.yaml'\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/visual_bert/direct.yaml', 'model=visual_bert', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=visual_bert.finetuned.hateful_memes.direct', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 58, in run\n",
      "    configuration = Configuration(args)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 210, in __init__\n",
      "    other_configs = self._build_other_configs()\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 227, in _build_other_configs\n",
      "    user_config = self._build_user_config(opts_config)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 253, in _build_user_config\n",
      "    user_config = load_yaml(self.config_path)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 30, in load_yaml\n",
      "    raise e\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 23, in load_yaml\n",
      "    mapping = OmegaConf.load(abs_f)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/omegaconf/omegaconf.py\", line 246, in load\n",
      "    with io.open(os.path.abspath(file_), \"r\", encoding=\"utf-8\") as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/jupyter/meme_hateful_detection/configs/visual_bert/direct.yaml'\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/vilbert/from_cc.yaml', 'model=vilbert', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=vilbert.finetuned.hateful_memes.from_cc_original', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 58, in run\n",
      "    configuration = Configuration(args)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 210, in __init__\n",
      "    other_configs = self._build_other_configs()\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 227, in _build_other_configs\n",
      "    user_config = self._build_user_config(opts_config)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 253, in _build_user_config\n",
      "    user_config = load_yaml(self.config_path)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 30, in load_yaml\n",
      "    raise e\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 23, in load_yaml\n",
      "    mapping = OmegaConf.load(abs_f)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/omegaconf/omegaconf.py\", line 246, in load\n",
      "    with io.open(os.path.abspath(file_), \"r\", encoding=\"utf-8\") as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/jupyter/meme_hateful_detection/configs/vilbert/from_cc.yaml'\n",
      "Namespace(config_override=None, local_rank=None, opts=['config=../configs/visual_bert/from_coco.yaml', 'model=visual_bert', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_zoo=visual_bert.finetuned.hateful_memes.from_coco', 'evaluation.predict=true'])\n",
      "/home/jupyter/mmf/mmf/utils/configuration.py:527: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.\n",
      "  \"Device specified is 'cuda' but cuda is not present. \"\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/bin/mmf_predict\", line 11, in <module>\n",
      "    load_entry_point('mmf', 'console_scripts', 'mmf_predict')()\n",
      "  File \"/home/jupyter/mmf/mmf_cli/predict.py\", line 11, in predict\n",
      "    run(predict=True)\n",
      "  File \"/home/jupyter/mmf/mmf_cli/run.py\", line 58, in run\n",
      "    configuration = Configuration(args)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 210, in __init__\n",
      "    other_configs = self._build_other_configs()\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 227, in _build_other_configs\n",
      "    user_config = self._build_user_config(opts_config)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 253, in _build_user_config\n",
      "    user_config = load_yaml(self.config_path)\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 30, in load_yaml\n",
      "    raise e\n",
      "  File \"/home/jupyter/mmf/mmf/utils/configuration.py\", line 23, in load_yaml\n",
      "    mapping = OmegaConf.load(abs_f)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/omegaconf/omegaconf.py\", line 246, in load\n",
      "    with io.open(os.path.abspath(file_), \"r\", encoding=\"utf-8\") as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/jupyter/meme_hateful_detection/configs/visual_bert/from_coco.yaml'\n"
     ]
    }
   ],
   "source": [
    "for index, row in df_model_config.iterrows():\n",
    "    model_baseline = row['baseline']\n",
    "    model_key = row['model_key']\n",
    "    model_pretrained_key = row['pretrained_key']\n",
    "    baseline_config = row['baseline_config']\n",
    "    custom_config = row['custom_config']\n",
    "    str_exec = f'mmf_predict config=../{baseline_config} model={model_key} dataset=hateful_memes run_type=test checkpoint.resume_zoo={model_pretrained_key}'\n",
    "#     print(str_exec)\n",
    "    !{str_exec}\n",
    "#     MMF_USER_DIR=\".\" mmf_run config=\"configs/experiments/defaults.yaml\"  model=concat_vl dataset=hateful_memes training.num_workers=0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!MMF_USER_DIR=\"..\" mmf_run config=\"/home/jupyter/meme_hateful_detection/configs/unimodal/image.yaml\" model=unimodal_image dataset=hateful_memes training.num_workers=0\n",
    "# meme_hateful_detection/configs/unimodal/image.yaml\n",
    "# !mmf_run config=projects/hateful_memes/configs/unimodal/image.yaml       model=unimodal_image dataset=hateful_memes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mmf.common.registry import registry\n",
    "\n",
    "model_cls = registry.get_model_class(\"unimodal_image\")\n",
    "model = model_cls.from_pretrained(\"unimodal_image.hateful_memes.images\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "type(model)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Training\n",
    "!mmf_run config=projects/hateful_memes/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Evaluation\n",
    "!mmf_run config=projects/hateful_memes/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes run_type=val"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Predictions\n",
    "#Val\n",
    "!mmf_predict config=projects/hateful_memes/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes run_type=val\n",
    "\n",
    "#Test\n",
    "!mmf_predict config=projects/hateful_memes/configs/mmbt/defaults.yaml model=mmbt dataset=hateful_memes run_type=test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Evaluating Pretrained Models\n",
    "# Validation set, use the following command:\n",
    "# mmf_run config=projects/hateful_memes/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes run_type=val checkpoint.resume_zoo=<REPLACE_WITH_PRETRAINED_ZOO_KEY>\n",
    "# !mmf_run config=projects/hateful_memes/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes run_type=val checkpoint.resume_zoo=unimodal_image.hateful_memes.images\n",
    "\n",
    "# To generate predictions using pretrained models, use the following command:\n",
    "    \n",
    "!mmf_predict config=/home/jupyter/meme_hateful_detection/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes run_type=test checkpoint.resume_zoo=unimodal_image.hateful_memes.images\n",
    "# mmf_predict config=projects/hateful_memes/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes run_type=test checkpoint.resume_zoo=<R"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "os.system('ls -l')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# os.system(str_exec)\n",
    "\n",
    "# myCmd = os.popen(str_exec).read()\n",
    "# print(myCmd)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mmf.common.registry import registry\n",
    "\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.autograd import Variable\n",
    "\n",
    "# # Defining Model\n",
    "# class LinearRegressor(nn.Module):\n",
    "#     def __init__(self, inp_size, require_bias=True):\n",
    "#         super(LinearRegressor, self).__init__()\n",
    "#         self.linear = nn.Linear(in_features=inp_size, out_features=1, bias=require_bias)\n",
    "    \n",
    "#     def forward(self, inp_batch):\n",
    "#         return self.linear(inp_batch)\n",
    "    \n",
    "# Creating sample data for sum of 3 elements\n",
    "X = []\n",
    "for i in range(2):\n",
    "    for j in range(2):\n",
    "        for k in range(2):\n",
    "            X.append([i, j, k])\n",
    "\n",
    "y = map(lambda x: x[0] + x[1] + x[2], X)\n",
    "X = Variable(torch.FloatTensor(X), requires_grad=False)\n",
    "y = Variable(torch.FloatTensor(y), requires_grad=False)\n",
    "\n",
    "# Creating model and defining loss function and optimizer\n",
    "model_cls = registry.get_model_class(\"unimodal_image\")\n",
    "model = model_cls.from_pretrained(\"unimodal_image.hateful_memes.images\")\n",
    "loss_fn = nn.MSELoss()\n",
    "optim = torch.optim.Adam(model.parameters())\n",
    "\n",
    "# Training the model\n",
    "for epoch in range(2):\n",
    "    optim.zero_grad()\n",
    "    \n",
    "    out = model(X)\n",
    "    loss = loss_fn(out, y)\n",
    "    \n",
    "    loss.backward()\n",
    "    optim.step()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'pycuda'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-1-34b2993cf8e7>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mtorch\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mpycuda\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdriver\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mcuda\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0mcuda\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;31m# from __future__ import print_function\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;31m# import torch\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'pycuda'"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import pycuda.driver as cuda\n",
    "cuda.init()\n",
    "# from __future__ import print_function\n",
    "# import torch\n",
    "# x = torch.rand(5, 3)\n",
    "# print(x)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "False"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import torch\n",
    "torch.cuda.is_available()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.5.0\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "print(torch.__version__)\n",
    "# torch.zeros(1).cuda()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "environment": {
   "name": "pytorch-gpu.1-4.m46",
   "type": "gcloud",
   "uri": "gcr.io/deeplearning-platform-release/pytorch-gpu.1-4:m46"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
